name: Deploy React App to CloudFront (Development)

on:
  push:
    branches:
      - development  # Deploy only when this branch is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development  # GitHub environment name

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci
      
    - name: Download environment file from S3
      run: |
        aws s3 cp s3://tnt-development-new/environment-variables/config-ui/.env .env  

    - name: Build React App
      run: npm run build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Deploy to S3
      run: |
        aws s3 sync build/ s3://${{ vars.S3_BUCKET_NAME }}

    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ vars.DISTRIBUTION_ID }} \
          --paths "/*"

